VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.network :forwarded_port, guest: 80, host: 8888

  config.vm.network :private_network, ip: "33.33.33.10"

  config.vm.network :public_network

  config.ssh.forward_agent = true

  config.vm.synced_folder "../src", "/var/www/"

  config.vm.provider :virtualbox do |vb|

  vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

end
